### ISSUE TITLE
Can't save game skyrimtogether

### ISSUE THREAD

**Issue by poned101** [SkyrimTogether/issues-launcher#32] opened 2019-05-26 11:50 UTC
I'm not sure whether this is a bug or something on my end, but i am not able to save if i launch Skyrim through the harbor launcher, it says that my game save is corrupt, and i am not able to create a new save or quicksave. Opening Skyrim through steam gives me full save functions though. Any tips?

**Comment by Pokang** [comment] 2019-05-26 11:51
You're on the wrong board, and it is also a duplicate of this issue: https://github.com/SkyrimTogether/issues-game/issues/281

**Closed by Pokang** 2019-05-26 11:51 UTC
