### ISSUE TITLE
Crashes while using Teamviewer

### ISSUE THREAD

**Issue by Soriaki** [SkyrimTogether/issues-launcher#47] opened 2019-08-01 11:46 UTC
## Description

When I use Teamviewer the game crashes instantly, and I can't open it again until I stop the connection on Teamviewer. Its not a big problem for me, I just let u know that bug.

## Steps to reproduce

How to reproduce this issue:

Start the game with the Skyrim together launcher.

## Reproduction rate

Always

## Your environment

* Launcher version:

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):

    * Windows 10 x64

## Final checks for the reporter

- [ ] I have browsed through the other issues and confirmed that this issue has not been reported already
- [ ] I made sure that I have applied the template for my bug report

**Comment by Pokang** [comment] 2019-08-01 16:09
I have fixed tons of people's mods through Teamviewer, launched it and even played it through Teamviewer and never got that issue. Therefore, I am not able to reproduce it, closing accordingly.
You're also posting this issue in the wrong issueboard, this one is for launcher issues only.

**Closed by Pokang** 2019-08-01 16:09 UTC
