### ISSUE TITLE
'Play' button fails to launch game without error

### ISSUE THREAD

**Issue by ActionCactus** [SkyrimTogether/issues-launcher#5] opened 2019-01-28 18:57 UTC
## Description

Hitting 'Play' begins Harbor's initialization sequence but then stops unexpectedly without error.  Seems to be tied with modlist modification, particularly while the launcher is open.

This seems to be similar to the `Skyrim Together Inconsistent Launch` issue detailed [here](https://old.reddit.com/r/SkyrimTogether/comments/ajxkwr/all_known_fixes_for_issues_with_skyrim_together/), but I figured a task should be filed.

Restarting the launcher generally fixes the issue.

## STR

How to reproduce this issue:

1. Start the launcher.
2. Connect login.
3. Hit 'Play'
4. Note cmd prompt pops up and begins client initialization
5. Note cmd prompt closes unexpectedly without error
6. Note the 'Play' button changes text to indicate the game is launching but then nothing happens and it reverts to its original state.

## Reproduction Rate

Can reliably reproduce when modifying mod list.  Seems to be more frequent if mod list is modified while launcher is open, thought this can fairly reliably be reproduced either way.

## Expected Result

The game should either launch or an error should be displayed to the user. 

## Environment

* Launcher version:
I believe it's 1.0 or 1.03, can't remember which.  Filing from work and will re-check when I get home.

* Game edition:
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 10 x64

**Comment by Ueine** [comment] 2019-01-28 19:00
just spam it, its the broken Patreon api problem.

**Comment by Pokang** [comment] 2019-01-28 19:13
This has nothing to do with Patreon.

**Comment by ActionCactus** [comment] 2019-01-28 19:19
Thanks for clearing that up Pokang.  Regardless it does appear to me that 'just spamming it' tends to fix the problem, particularly if you restart the launcher (adding this to the issue now; sorry about that).

If there's a log somewhere that you'd like me to attach could you please indicate where I may find it?

**Comment by ActionCactus** [comment] 2019-01-29 01:56
Hey Pokang, I've repeated the STR in addition to trying other methods and I couldn't reproduce it!  Nice work on the update - the team deserves more credit than Bethesda themselves (don't tell the Zenimax guy I said that).

**Comment by WopsS** [comment] 2019-01-29 10:37
Hello,

Thank for the report, we should add a text saying that the game crashed on launch instead of just reverting the play button to normal.

**Comment by Furitasma** [comment] 2019-02-12 08:08
I‘ve got the same issue when I hadn’t installed SKSE.

**Comment by REGalram** [comment] 2019-02-13 12:02
I've got this exact same issue with the newest version of the launcher. No errors in the debug console, just opens, closes, and nothing happens.

**Comment by Pokang** [comment] 2019-02-13 16:08
@Furitasma @REGalram Can you guys confirm me that your Steam was running beforehand and that Vanilla SE launches normally?

**Comment by REGalram** [comment] 2019-02-13 16:32
@Pokang  Yep to both, also tried running it as admin and compatibility modes. Tried clean reinstall of both harbour and Skyrim SE.

**Comment by Pokang** [comment] 2019-02-13 17:00
Just so you know, uninstalling Harbor does not uninstall the mod files, you could try reinstalling them by deleting these, in your game folder : 
`Data/Online
locales
swiftshader
cef.pak
cef_100_percent.pak
cef_200_percent.pak
cef_extensions.pak
chrome_elf.dll
d3dcompiler_43.dll
d3dcompiler_47.dll
devtools_resources.pak
icudtl.dat
libcef.dll
libEGL.dll
libGLESv2.dll
natives_blob.bin
SkyrimTogether_r.dll
snapshot_blob.bin
st_loader_r.exe
st_process_r.exe
st_steam_api64.dll
v8_context_snapshot.bin`
And then relaunching the launcher with administrator right, and antivirus disabled.
Keep me updated!

**Comment by REGalram** [comment] 2019-02-13 17:13
Tried that, same result.

What I noticed though is that I have no "st_steam_api64.dll" file, could that be a reason?

**Comment by Pokang** [comment] 2019-02-13 17:56
No, that's a file that we stopped pushing a while ago, it shouldn't even be there in the first place.
Can you contact me on Discord, tag me on our server in a public chat @Pokang#7174

**Comment by Pokang** [comment] 2019-02-13 18:32
After further investigation we discovered that a software called "Bins" that is made by "Stardock Corporation" was conflicting with our mod for @regalram.
 
My best guess is that like us it uses CEF and that CEF doesn't like running 2 instances of itself, will need confirmation from other devs though.

@Furitasma You can as well contact me on Discord @Pokang#7174 if you want me to look into your issue if you're still experiencing it.

**Comment by Kiaos** [comment] 2019-05-26 17:47
I have this issue too. 1.0.5 Harbor

**Comment by bigogre55** [comment] 2019-05-29 03:40
i had this same issue. the problem is more than likely an incompatible mod.  i fixed it by taking a screen recording of the launch window and then played it back to see the last line of output before the window closed. mine was trying to load a mod, so i disabled the mod and it worked fine.

**Comment by Kiaos** [comment] 2019-06-01 02:08
the reason mine didnt work is cause HDT physics would ctd harbor when I removed any type of physics it worked.

**Comment by bacitoto** [comment] 2019-06-05 14:01
Can confirm

hdtSSEFramework 1 5 73 3
and/or
hdtSSEPhysics 1 5 73 3

Won't launch the game
I have other SKSE plugins and they are working fine

**Comment by FennecTheFennec** [comment] 2019-06-12 18:54
Got this problem too.

**Comment by Pokang** [comment] 2019-06-12 21:03
@FennecTheFennec The reasons all of the users above were not able to launch the mod were all about other mods or third party software, as far as the closed beta.
Please try uninstalling anything that could interfere with the mod and try doing a clean install.
I will close this issue since everyone is using it for their own problem, please reopen one if you're still having trouble after my instructions, thank you!

**Closed by Pokang** 2019-06-12 21:03 UTC
Labels: comp: main, comp: renderer, priority: 5 (critical), type: bug
